version: "3"

services:
    server:
        image: short-story-api
        container_name: short-story-api
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        networks:
            - short-story-network
        depends_on:
            - mongo
            - redis
        volumes:
            - .:/usr/src/
        links:
            - mongo
            - redis
            - client
        # environment:
        #     - REDIS_PORT_6379_TCP_ADDR:"redis:6379"
        #     - MONGO_PORT_27017_TCP_ADDR:"mongodb://mongo:27017"

    client:
        image: short-story-client
        container_name: short-story-client
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        networks:
            - short-story-network
        volumes:
            - .:/usr/src

    mongo:
        image: mongo:4
        container_name: short-story-mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - short-story-mongo-volume:/data/db
        networks:
            - short-story-network

    redis:
        image: redis:6.2.2-alpine
        container_name: short-story-redis
        restart: on-failure
        ports:
            - "6379:6379"
        networks:
            - short-story-network
        volumes:
            - short-story-redis-volume:/data/redis

volumes:
    short-story-mongo-volume:
    short-story-redis-volume:

networks:
    short-story-network:
        driver: bridge